### ISSUE TITLE
Log Insight 4.5 and vRO 7.3 Issues

### ISSUE THREAD

**Issue by vchrisst** [vmw-loginsight/webhook-shims#58]
Hi Team,

at the moment I am playing somewhat around with your shim. I use the docker Image. I have vRealize Log Inisght in Version 4.5 and the vRealize Orchestrator in Version 7.3 in usage. I configured everything like documented and also made an Alarm Webhook notification in Log Inisght. From there I can see that the Webhook arrives in the Shim but at the Moment I am not able to forward the message to vRO. The components can communicate with each other (no Firewalls) and when I try to manually access the URLs everything works fine. I know that you doesn’t give support but maybe there is a hint were I have to search.

Here are the relevant Logs:

2017-11-29 05:17:52,335 INFO Parsed={'info': u'Nov 29 06:14:27 MyTest: client1', 'HasMoreResults': 'False', 'NumHits': '1', 'url': u'https://192.168.120.195/s/wi02iy', 'fields': [{'content': 'False', 'name': 'HasMoreResults'}, {'content': '1', 'name': 'NumHits'}], 'Messages': [{u'text': u'Nov 29 06:14:27 MyTest: client1', u'fields': [{u'content': u'192.168.116.11', u'name': u'hostname'}, {u'content': u'MyTest', u'name': u'appname'}, {u'content': u'192.168.116.11', u'name': u'__li_source_path'}], u'timestamp': 1511933076560}], 'editurl': u'https://192.168.120.195/s/0mrt7v', 'AlertName': u'MyTest', 'moreinfo': u'MyTest\n\nNov 29 06:14:27 MyTest: client1\n\nYou can view this alert by clicking: https://192.168.120.195/s/wi02iy\nYou can edit this alert by clicking: https://192.168.120.195/s/0mrt7v', 'hookName': 'Log Insight', 'color': 'red', 'icon': 'http://blogs.vmware.com/management/files/2015/04/li-logo.png'}
2017-11-29 05:17:52,336 INFO URL=https://192.168.101.206:8182/vco/api/workflows/4ebdca02-7f70-48ee-987a-f07e28a9a62e/executions
2017-11-29 05:17:52,336 INFO Headers={'Content-type': 'application/json'}
2017-11-29 05:17:52,337 INFO Body={"parameters": [{"name": "messages", "scope": "local", "type": "string", "value": {"string": {"value": "eyJBbGVydFR5cGUiOjEsIkFsZXJ0TmFtZSI6IlNlY3VyaXR5YnJlYWsiLCJTZWFyY2hQZXJpb2QiOjMwMDAwMCwiSGl0Q291bnQiOjAuMCwiSGl0T3BlcmF0b3IiOjIsIm1lc3NhZ2VzIjpbeyJ0ZXh0IjoiTm92IDI5IDA2OjE0OjI3IHNlY3VyaXR5YnJlYWs6IGNsaWVudC12Y29wb3J0YWwuZGUiLCJ0aW1lc3RhbXAiOjE1MTE5MzMwNzY1NjAsImZpZWxkcyI6W3sibmFtZSI6Imhvc3RuYW1lIiwiY29udGVudCI6IjEwLjEwLjExNi4xMSJ9LHsibmFtZSI6ImFwcG5hbWUiLCJjb250ZW50Ijoic2VjdXJpdHlicmVhayJ9LHsibmFtZSI6Il9fbGlfc291cmNlX3BhdGgiLCJjb250ZW50IjoiMTAuMTAuMTE2LjExIn1dfV0sIkhhc01vcmVSZXN1bHRzIjpmYWxzZSwiVXJsIjoiaHR0cHM6Ly8xMC4xMC4xMjAuMTk1L3Mvd2kwMml5IiwiRWRpdFVybCI6Imh0dHBzOi8vMTAuMTAuMTIwLjE5NS9zLzBtcnQ3diIsIkluZm8iOm51bGwsIlJlY29tbWVuZGF0aW9uIjpudWxsLCJOdW1IaXRzIjoxfQ=="}}}, {"name": "alertName", "scope": "local", "type": "string", "value": {"string": {"value": "MyTest"}}}, {"name": "hitCount", "scope": "local", "type": "number", "value": {"number": {"value": "1"}}}]}
2017-11-29 05:17:52,337 INFO Check=False
2017-11-29 05:17:52,342 DEBUG Starting new HTTPS connection (1): 192.168.101.206
2017-11-29 05:17:52,344 ERROR Can't create new payload. Check code and try again.
Traceback (most recent call last):
  File "/root/webhook-shims/loginsightwebhookdemo/__init__.py", line 222, in callapi
    r = requests.request(method, url, headers=headers, data=payload, verify=check)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='192.168.101.206', port=8182): Max retries exceeded with url: /vco/api/workflows/4ebdca02-7f70-48ee-987a-f07e28a9a62e/executions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd5f1e33150>: Failed to establish a new connection: [Errno 111] Connection refused',))
[2017-11-29 05:17:52,346] ERROR in app: Exception on /endpoint/vro/4ebdca02-7f70-48ee-987a-f07e28a9a62e [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/webhook-shims/loginsightwebhookdemo/vrealizeorchestrator.py", line 131, in vro
    return callapi("https://" + VROHOSTNAME + "/vco/api/workflows/" + WORKFLOWID + "/executions", 'post', json.dumps(payload), HEADERS, AUTH, VERIFY)
  File "/root/webhook-shims/loginsightwebhookdemo/__init__.py", line 222, in callapi
    r = requests.request(method, url, headers=headers, data=payload, verify=check)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='192.168.101.206', port=8182): Max retries exceeded with url: /vco/api/workflows/4ebdca02-7f70-48ee-987a-f07e28a9a62e/executions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd5f1e33150>: Failed to establish a new connection: [Errno 111] Connection refused',))
2017-11-29 05:17:52,347 INFO 192.168.120.195 - - [29/Nov/2017 05:17:52] "POST /endpoint/vro/4ebdca02-7f70-48ee-987a-f07e28a9a62e HTTP/1.1" 500 -

Thanks
Chris

**Comment by alanjcastonguay** [comment]
>Failed to establish a new connection: [Errno 111] Connection refused

That implies a network path problem between the shim and VRO. 

>The components can communicate with each other (no Firewalls) and when I try to manually access the URLs everything works fine.

Can you prove this, such as using `curl` on the same machine running the shim, to reach the same VRO server?

**Comment by alanjcastonguay** [comment]
I doubt the payload body matters, and this should produce the same Connection Refused symptom:

`curl -v -X POST https://192.168.101.206:8182/vco/api/workflows/4ebdca02-7f70-48ee-987a-f07e28a9a62e/executions`

**Comment by vchrisst** [comment]
Hi Alan,

you were right. It was a network problem (I made a typo in the Port!). After the change I had to restart the server and everything works liked expected!

Thanks for your help!
Chris
